name: belin_zayy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: 
  change_app_package_name: 
  firebase_auth: ^4.9.0
  firebase_core: 
  cloud_firestore: 
  starlight_country_picker:
    git:
      url: https://github.com/YeMyoAung/starlight_country_picker.git  
  firebase_core_platform_interface: 
  fancy_shimmer_image:
  card_swiper: 
  uuid:
  fluttertoast: 
  badges:
  add_to_cart_animation: 
  flutter_staggered_grid_view:
  connectivity_plus:  
  font_awesome_flutter: 
  intl: 
  flutter_neumorphic: 
  image_picker: 
  firebase_storage: 
  cached_network_image: 
  get_it: ^7.6.0
  geolocator: 
  geocoding: 
  rive: ^0.11.4
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: any
flutter_native_splash:
  color: "#ffffff"  
  image: "images/logo.png"
 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/cat/
    - images/landing/
    - images/offres/
    - images/riv/  

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
